### PR TITLE
Deprioritze presentation of meta-content about editing the handbook.

### PR DESCRIPTION
**Pull request by zaneselvans**
@bendnorman the docs build fails on this but I'm not understanding what the problem is. Something about duplicate headers / links. I can look into it but I thought you might just know the answer immediately...

### CODE REVIEW

**Comment by bendnorman** [comment]
For whatever reason, Myst / sphinx fails locally when you have [target headers](https://jupyterbook.org/en/stable/reference/cheatsheet.html#target-headers) in a markdown that is added to the index using the `include` directive. A work around is to move the content of `catalyst_101.md` in `index.md`.

**Comment by zaneselvans** [comment]
If it builds successfully on RTD it seems like we should be able to fix this, but also it's really too long and granular for the front page. There should be an actual short intro of some kind.

Do you know why there isn't a table of contents for the page in the upper right hand side, like there is for [the main PUDL docs](https://catalystcoop-pudl.readthedocs.io/en/latest/)?

**Comment by bendnorman** [comment]
I spent about 30 min trying to debug the duplicate label issue. It seems like `{include}` is breaking the markdown cross-referencing and the table of contents in the upper right-hand side. What are your thoughts on moving catalyst_101 back to `{toctree}`? I'm happy to keep debugging but I'm not sure it's worth the time.

**Comment by zaneselvans** [comment]
I think creating a new front page with an intro to the handbook and having Catalyst 101 be a page inside it sounds good.

**Comment by bendnorman** [comment]
I made Catalyst 101 a page again and created a table of contents on the front page to explain what's in the handbook.

**Comment by zaneselvans** [comment]
@bendnorman thanks for futzing with this. Looks good!

**Review by bendnorman — APPROVED** [review]

**Pull request merged**
